server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BTG?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Laurita2013
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.office365.com
    port: 587
    username: #TuCorreo de office365
    password: #TuContraseña de tu correo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.office365.com
      mail.debug: true
    default-encoding: UTF-8

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      display-request-duration: true
    api-docs:
      path: /v3/api-docs
      enabled: true

#  http://localhost:8080/v2/api-docs
#  http://localhost:8080/swagger-ui.html